polls/urls.py
from django.urls import path
from . import views


app_name = 'polls'
urlpatterns =[
    # path( route,view,kwargs,name)
    path('',views.IndexView.as_view(), name='index'),
    path('<int:pk>/detail', views.DetailView.as_view(),name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path("<int:question_id>/vote/", views.vote, name='vote'),
]

tutoriald/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('polls/',include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days = 1)
        
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete = models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from .models import  Choice,Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


'''def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    
    #template = loader.get_template('polls/index.html')
    #latest_question_list = Question.objects.all()
    #output = ','.join([q.question_text for q in latest_question_list])
    #return HttpResponse(output)
   
    context = {
        'latest_question_list': latest_question_list,
        
   
    }
    #return HttpResponse(template.render(context,request))
    return render(request,'polls/index.html',context)

def detail(request, question_id):
    #try:
        #question = Question.objects.get(pk=question_id)
    #except Question.DoesNotExist:
        #raise Http404("Question does not exist")
    #return render(request,'polls/detail.html',{'question':question})
    question = get_object_or_404(Question, pk = question_id)
    return render(request,'polls/detail.html',{'question': question})

  

def results(request,question_id):
    #response = 'you are looking at the results of question %s.'
    #return HttpResponse(response % question_id)
    #question = get_object_or_404(Question,pk=question_id)
    question = Question(pk=question_id)
    return render(request,'polls/results.html',{'question':question})'''

    
def vote(request,question_id):
    #return HttpResponse('you are voting on question %s.'% question_id)
    question = get_object_or_404(Question, pk=question_id)
   

    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
       
    except KeyError:
        
        return render(request,'polls/vote.html',{'question':question,
        'error_message':
        'You did not select  choice.',})
    else:
        selected_choice.votes +=1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results',args=(question.id,)))      

polls/templates/polls/detail.html
<h1> {{ question.question_text}}</h1>

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend>
            <h2>{{question.question_text}}</h2>
        </legend>
        {% if error_message %}
        <p>
            <strong>
                {{error_message}}
            </strong>
        </p>
        {% endif %}
        
        {% for choice in question.choice_set.all %}
        
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{choice.id}}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type='submit' value="Vote">
</form>

polls/templates/polls/index.html
<h1>Index Page</h1>


{% if latest_question_list %}



        <ul>
        {% for question in latest_question_list %}
       
        <!-- for não funciona   -->
        <!---li><a href="/polls/{{question.id}}/"> {{
                question.question_text}}</a></li--->
        <li>
                <a href="{% url 'polls:vote' question.id %}">{{ question.question_text}}</a>        
        </li>        
        {% endfor %}
        </ul>
{%  else %}
    
    <p>No polls are avaible.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{question.question_text}}</h1>


<ul>
    {% for choice in question.choice_set.all %}
    <li>
        {{choice.choice_text}} -- {{choice.votes}} vote{{choice.votes|pluralize}}
    </li>
    {% endfor %}
</ul>
<a href="{% url 'polls:vote' question.id%}">Vote again ?</a>
<a href="{% url 'polls:index' %}">See other poll?</a>

polls/templates/polls/vote.html
<h1>Vote</h1>

<h3> {{ question.question_text}}</h3>

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend>
            <h2>{{question.question_text}}</h2>
        </legend>
        {% if error_message %}
        <p>
            <strong>
                {{error_message}}
            </strong>
        </p>
        {% endif %}
        
        {% for choice in question.choice_set.all %}
        
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{choice.id}}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type='submit' value="Vote">
</form>